// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9Mwq8YfknTqbDd6alhgwd-kBzptTQoY',
    appId: '1:513454520108:web:2d372d76546ec2bed8de89',
    messagingSenderId: '513454520108',
    projectId: 'task-management-c1720',
    authDomain: 'task-management-c1720.firebaseapp.com',
    storageBucket: 'task-management-c1720.appspot.com',
    measurementId: 'G-YVZYB74F2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_nTwoxdqKvM5R-g0_o_XG-jytPhCxnc',
    appId: '1:513454520108:android:15315026c55e46e1d8de89',
    messagingSenderId: '513454520108',
    projectId: 'task-management-c1720',
    storageBucket: 'task-management-c1720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4FQFGmfkbLzTLjxVV-s2lYH5zwwtN9Y',
    appId: '1:513454520108:ios:40b7e420364f808dd8de89',
    messagingSenderId: '513454520108',
    projectId: 'task-management-c1720',
    storageBucket: 'task-management-c1720.appspot.com',
    iosClientId: '513454520108-dvjsprkc7evt2sf9sr6ap9qiv68p4j77.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4FQFGmfkbLzTLjxVV-s2lYH5zwwtN9Y',
    appId: '1:513454520108:ios:40b7e420364f808dd8de89',
    messagingSenderId: '513454520108',
    projectId: 'task-management-c1720',
    storageBucket: 'task-management-c1720.appspot.com',
    iosClientId: '513454520108-dvjsprkc7evt2sf9sr6ap9qiv68p4j77.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
